apiVersion: v1
kind: Service
metadata:
  name: dos-game
  labels:
    app: dos-game
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
    name: http
  selector:
    app: dos-game
  type: NodePort
