apiVersion: apps/v1
kind: Deployment
metadata:
  name: dos-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dos-game
  template:
    metadata:
      labels:
        app: dos-game
    spec:
      containers:
      - name: dos-game-container
        image: public.ecr.aws/o9r8h0v8/dos-game-repo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
